-- ── GEO Prompts ─────────────────────────────────────────────────────────────
-- Stores real prompts entered by users (manually or generated by AI).
-- This table acts as a growing prompt database to help AI generate better
-- prompts based on real user data.

CREATE TABLE IF NOT EXISTS geo_prompts (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  prompt      text        NOT NULL,
  topic       text,
  source      text        NOT NULL DEFAULT 'manual'
                          CHECK (source IN ('manual', 'generated')),
  site_theme  text,
  user_id     uuid        REFERENCES auth.users(id) ON DELETE SET NULL,
  run_id      uuid        REFERENCES workflow_runs(id) ON DELETE SET NULL,
  created_at  timestamptz DEFAULT now()
);

ALTER TABLE geo_prompts ENABLE ROW LEVEL SECURITY;

-- Owners can read their own prompts
CREATE POLICY "geo_prompts_owner_select" ON geo_prompts
  FOR SELECT USING (auth.uid() = user_id OR user_id IS NULL);

-- Anyone authenticated can insert
CREATE POLICY "geo_prompts_insert" ON geo_prompts
  FOR INSERT WITH CHECK (auth.uid() = user_id OR user_id IS NULL);

CREATE INDEX IF NOT EXISTS geo_prompts_user_id_idx  ON geo_prompts(user_id);
CREATE INDEX IF NOT EXISTS geo_prompts_created_at_idx ON geo_prompts(created_at DESC);
CREATE INDEX IF NOT EXISTS geo_prompts_source_idx   ON geo_prompts(source);
